### ISSUE TITLE
Uncaught Error: Class 'Razorpay\Api\Webhook' not found

### ISSUE THREAD

**Issue by hitendra52** [razorpay/razorpay-magento#293]
Magento ver. 2.3.3
Razorpay module version : 3.7.1

How to reproduce :
1.  Login to Magento admin 
2. Stores > Configuration >Sales >Payment methods >Razorpay > Webhook Enabled
3. Enable/Disable 
4. Save 

Error :
```
Fatal error: Uncaught Error: Class 'Razorpay\Api\Webhook' not found in /****/******/public_html/vendor/razorpay/razorpay/src/Api.php:67 
Stack trace: #0 /****/******/public_html/vendor/razorpay/magento/Observer/AfterConfigSaveObserver.php(152): Razorpay\Api\Api->__get('webhook') 
#1 /****/******/public_html/vendor/razorpay/magento/Observer/AfterConfigSaveObserver.php(84): Razorpay\Magento\Observer\AfterConfigSaveObserver->getExistingWebhook() 
#2 /****/******/public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Razorpay\Magento\Observer\AfterConfigSaveObserver->execute(Object(Magento\Framework\Event\Observer)) 
#3 /****/******/public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Razorpay\Magento\Observer\AfterConfigSaveObserver), Object(Magento\Framework\Event\Observer)) 
#4 /****/******/public_html/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invo in /****/******/public_html/vendor/razorpay/razorpay/src/Api.php on line 67
```

**Comment by ramth05** [comment]
@hitendra52 , If you are using composer based installation please upgrade Razorpay sdk as well.

**Comment by ramth05** [comment]
closing as there is no response.
