### ISSUE TITLE
Order is not placing with latest version.

### ISSUE THREAD

**Issue by himanshuv4** [razorpay/razorpay-magento#471]
While placing the order I am getting below error in console.

Uncaught TypeError: Cannot read properties of undefined (reading 'reject')
    at Object.error (razorpay-method.min.js:7:478)
    at fire (jquery.min.js:212:223)
    at Object.fireWith [as rejectWith] (jquery.min.js:218:181)
    at done (jquery.min.js:628:166)
    at XMLHttpRequest.callback (jquery.min.js:655:15)

**Comment by yashgit891** [comment]
@himanshuv4 request you to raise a ticket with support team with more details of this.
