### ISSUE TITLE
Error in Generates DI configuration 

### ISSUE THREAD

**Issue by ashok1421** [razorpay/razorpay-magento#483]
Hello @yashgit891 ,
After installed Razorpay module when we run command php bin/magento setup:di:compile.
It throw the error.
```
PHP Fatal error:  Uncaught Error: Class 'WpOrg\Requests\Autoload' not found in project/vendor/razorpay/magento/Model/TrackPluginInstrumentation.php:23
Stack trace:
#0 project/vendor/composer/ClassLoader.php(576): include()
#1 project/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/Users/ashokmah...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Razorpay\\Magent...')
#3 [internal function]: spl_autoload_call('Razorpay\\Magent...')
#4 project/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('Razorpay\\Magent...')
#5 project/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('Razorpay\\Magent...', '/Users/ashokmah...')
#6 /Users/ashokmahyvanshi/Documents/projec in project/vendor/razorpay/magento/Model/TrackPluginInstrumentation.php on line 23

Fatal error: Uncaught Error: Class 'WpOrg\Requests\Autoload' not found in project/vendor/razorpay/magento/Model/TrackPluginInstrumentation.php:23
Stack trace:
#0 project/vendor/composer/ClassLoader.php(576): include()
#1 project/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/Users/ashokmah...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Razorpay\\Magent...')
#3 [internal function]: spl_autoload_call('Razorpay\\Magent...')
#4 project/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('Razorpay\\Magent...')
#5 project/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('Razorpay\\Magent...', '/Users/ashokmah...')
#6 /Users/ashokmahyvanshi/Documents/projec in project/vendor/razorpay/magento/Model/TrackPluginInstrumentation.php on line 23
```
```
PHP Fatal error:  Uncaught Error: Class 'WpOrg\Requests\Autoload' not found in project/vendor/razorpay/magento/Model/System/Message/UpgradeMessageNotification.php:20
Stack trace:
#0 project/vendor/composer/ClassLoader.php(576): include()
#1 project/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/Users/ashokmah...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Razorpay\\Magent...')
#3 [internal function]: spl_autoload_call('Razorpay\\Magent...')
#4 project/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('Razorpay\\Magent...')
#5 project/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('Razorpay\\Magent...', '/Users/ashokmah...')
#6 /Users/ashokmahyvanshi/Documents/projec in project/vendor/razorpay/magento/Model/TrackPluginInstrumentation.php on line 23

Fatal error: Uncaught Error: Class 'WpOrg\Requests\Autoload' not found in project/vendor/razorpay/magento/Model/System/Message/UpgradeMessageNotification.php:20
Stack trace:
#0 project/vendor/composer/ClassLoader.php(576): include()
#1 project/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/Users/ashokmah...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Razorpay\\Magent...')
#3 [internal function]: spl_autoload_call('Razorpay\\Magent...')
#4 project/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('Razorpay\\Magent...')
#5 project/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('Razorpay\\Magent...', '/Users/ashokmah...')
#6 /Users/ashokmahyvanshi/Documents/projec in project/vendor/razorpay/magento/Model/TrackPluginInstrumentation.php on line 23
```

**Comment by yashgit891** [comment]
@ashok1421 what is the magento and php version being used?

**Comment by ashok1421** [comment]
@yashgit891 Magento2.4.1 php v7.4.33

**Comment by yashgit891** [comment]
@ashok1421 not able to reproduce at my end. Can you please tell if you installed plugin via composer or the code.zip file that we provide.

**Comment by ashok1421** [comment]
@yashgit891 composer
