### ISSUE TITLE
Class "WpOrg\Requests\Autoload" not found | Razorpay v4.1.5

### ISSUE THREAD

**Issue by sehajmathur** [razorpay/razorpay-magento#486]
While upgrading this extension in magento version 2.4.7 I am getting following error after running bin/magento setup:upgrade command:

> There is an error in /home/invinge/magento247/app/code/Razorpay/Magento/Model/TrackPluginInstrumentation.php at line: 22
> Class "WpOrg\Requests\Autoload" not found#0 /home/invinge/magento247/vendor/composer/ClassLoader.php(571): include()
> #1 /home/invinge/magento247/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/home/invinge/s...')
> #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Razorpay\\Magent...')
> #3 /home/invinge/magento247/vendor/magento/framework/GetParameterClassTrait.php(41): ReflectionClass->__construct('Razorpay\\Magent...')
> #4 /home/invinge/magento247/vendor/magento/framework/Code/Reader/ClassReader.php(42): Magento\Framework\Code\Reader\ClassReader->getParameterClass(Object(ReflectionParameter))
> #5 /home/invinge/magento247/vendor/magento/framework/ObjectManager/Definition/Runtime.php(50): Magento\Framework\Code\Reader\ClassReader->getConstructor('Razorpay\\Magent...')
> #6 /home/invinge/magento247/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Razorpay\\Magent...')
> #7 /home/invinge/magento247/vendor/magento/framework/ObjectManager/ObjectManager.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Razorpay\\Magent...', Array)
> #8 /home/invinge/magento247/setup/src/Magento/Setup/Model/Installer.php(1249): Magento\Framework\ObjectManager\ObjectManager->create('Razorpay\\Magent...')
> #9 /home/invinge/magento247/setup/src/Magento/Setup/Model/Installer.php(1667): Magento\Setup\Model\Installer->createSchemaDataHandler('Razorpay\\Magent...', 'Magento\\Framewo...')
> #10 /home/invinge/magento247/setup/src/Magento/Setup/Model/Installer.php(1055): Magento\Setup\Model\Installer->getSchemaDataHandler('Razorpay_Magent...', 'schema-upgrade')
> #11 /home/invinge/magento247/setup/src/Magento/Setup/Model/Installer.php(917): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema', Array)
> #12 /home/invinge/magento247/setup/src/Magento/Setup/Console/Command/UpgradeCommand.php(147): Magento\Setup\Model\Installer->installSchema(Array)
> #13 /home/invinge/magento247/vendor/symfony/console/Command/Command.php(326): Magento\Setup\Console\Command\UpgradeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #14 /home/invinge/magento247/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #15 /home/invinge/magento247/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\UpgradeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #16 /home/invinge/magento247/vendor/magento/framework/Console/Cli.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #17 /home/invinge/magento247/vendor/symfony/console/Application.php(175): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #18 /home/invinge/magento247/bin/magento(23): Symfony\Component\Console\Application->run()
> #19 {main}

**Comment by sanjay209** [comment]
Is there any fix for this issue yet?
